import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { Container } from "@/components/ui";
import { ProductGallery } from "@/components/product/ProductGallery";
import { ProductInfo } from "@/components/product/ProductInfo";
import { StickyBuyBar } from "@/components/product/StickyBuyBar";
import { RelatedProducts } from "@/components/product/RelatedProducts";
import { CustomerFeedback } from "@/components/product/CustomerFeedback";
import { getProductBySlug, getProductSlugs, getProducts } from "@/lib/api";
import { getLocalizedValue } from "@/lib/utils";
import type { Locale } from "@/i18n/config";

// Allow dynamic slugs not pre-generated by generateStaticParams
export const dynamicParams = true;

interface Props {
    params: Promise<{ locale: string; slug: string }>;
}

export async function generateMetadata({ params }: Props) {
    const { locale, slug } = await params;
    const product = await getProductBySlug(slug);

    if (!product) {
        return { title: "Product Not Found" };
    }

    const name = getLocalizedValue(product.name, locale as Locale);
    const description = getLocalizedValue(product.shortDescription, locale as Locale);

    return {
        title: `${name} - Plumé Cosmetics`,
        description,
        openGraph: {
            title: name,
            description,
            images: [product.thumbnail],
        },
    };
}

export default async function ProductDetailPage({ params }: Props) {
    const { locale, slug } = await params;
    setRequestLocale(locale);

    // Fetch product and all products in parallel
    const [product, allProducts] = await Promise.all([
        getProductBySlug(slug),
        getProducts(locale as Locale)
    ]);

    if (!product) {
        notFound();
    }

    const name = getLocalizedValue(product.name, locale as Locale);

    return (
        <>
            <section className="py-12 md:py-24 bg-white min-h-screen pb-32">
                <Container size="wide">
                    <div className="grid lg:grid-cols-2 gap-12 lg:gap-16">
                        {/* Gallery */}
                        <div className="lg:sticky lg:top-24 lg:self-start">
                            <ProductGallery images={product.images} productName={name} />
                        </div>

                        {/* Info */}
                        <div className="space-y-8">
                            <ProductInfo product={product} locale={locale as Locale} />
                        </div>
                    </div>
                </Container>
            </section>

            {/* Customer Feedback Section */}
            <CustomerFeedback productId={product.id} locale={locale as Locale} />

            {/* Related Products Section */}
            <RelatedProducts
                products={allProducts}
                currentProductId={product.id}
                locale={locale as Locale}
            />

            {/* Sticky Buy Bar at bottom */}
            <StickyBuyBar product={product} locale={locale as Locale} />
        </>
    );
}

export async function generateStaticParams() {
    const slugs = await getProductSlugs();
    return slugs.map((slug) => ({
        slug,
    }));
}
