/**
 * Admin Blog API Functions
 * Server-side CRUD operations for blog posts
 */

import { getAdminClient } from '../supabaseClient';
import type {
    Locale,
    CreateBlogPostRequest,
    BlogPostRow,
    BlogStatus,
} from '../types';

/**
 * Create a new blog post with translations and media
 */
export async function createBlogPost(input: CreateBlogPostRequest): Promise<BlogPostRow> {
    const supabase = getAdminClient();

    // 1. Create base blog post
    const { data: post, error: postError } = await supabase
        .from('blog_posts')
        .insert({
            status: input.status || 'draft',
            published_at: input.published_at || null,
            is_featured: input.is_featured ?? false,
            reading_time: input.reading_time || null,
        })
        .select()
        .single();

    if (postError) {
        console.error('Error creating blog post:', postError);
        throw postError;
    }

    // 2. Create translations
    if (input.translations && input.translations.length > 0) {
        const translations = input.translations.map((t) => ({
            blog_post_id: post.id,
            locale: t.locale,
            title: t.title,
            slug: t.slug || null, // Will be auto-generated by trigger if null
            excerpt: t.excerpt || null,
            content: t.content || null,
            seo_title: t.seo_title || null,
            seo_description: t.seo_description || null,
            seo_keywords: t.seo_keywords || null,
            og_image_url: t.og_image_url || null,
        }));

        const { error: translationError } = await supabase
            .from('blog_translations')
            .insert(translations);

        if (translationError) {
            // Rollback: delete post
            await supabase.from('blog_posts').delete().eq('id', post.id);
            console.error('Error creating blog translations:', translationError);
            throw translationError;
        }
    }

    // 3. Create media
    if (input.media && input.media.length > 0) {
        const media = input.media.map((m, index) => ({
            blog_post_id: post.id,
            url: m.url,
            alt_text: m.alt_text || null,
            type: m.type || 'image',
            is_featured: m.is_featured ?? (index === 0),
            caption: m.caption || null,
            sort_order: index,
        }));

        const { error: mediaError } = await supabase
            .from('blog_media')
            .insert(media);

        if (mediaError) {
            console.error('Error creating blog media:', mediaError);
            throw mediaError;
        }
    }

    return post as BlogPostRow;
}

/**
 * Update an existing blog post
 */
export async function updateBlogPost(
    id: string,
    input: Partial<CreateBlogPostRequest>
): Promise<BlogPostRow> {
    const supabase = getAdminClient();

    // 1. Update base post if needed
    const postUpdate: Record<string, unknown> = {};
    if (input.status !== undefined) postUpdate.status = input.status;
    if (input.published_at !== undefined) postUpdate.published_at = input.published_at;
    if (input.is_featured !== undefined) postUpdate.is_featured = input.is_featured;
    if (input.reading_time !== undefined) postUpdate.reading_time = input.reading_time;

    if (Object.keys(postUpdate).length > 0) {
        const { error: postError } = await supabase
            .from('blog_posts')
            .update(postUpdate)
            .eq('id', id);

        if (postError) {
            console.error('Error updating blog post:', postError);
            throw postError;
        }
    }

    // 2. Update translations (upsert by locale)
    if (input.translations) {
        for (const t of input.translations) {
            const { error } = await supabase
                .from('blog_translations')
                .upsert({
                    blog_post_id: id,
                    locale: t.locale,
                    title: t.title,
                    slug: t.slug,
                    excerpt: t.excerpt,
                    content: t.content,
                    seo_title: t.seo_title,
                    seo_description: t.seo_description,
                    seo_keywords: t.seo_keywords,
                    og_image_url: t.og_image_url,
                }, { onConflict: 'blog_post_id,locale' });

            if (error) {
                console.error('Error updating blog translation:', error);
                throw error;
            }
        }
    }

    // 3. Replace media if provided
    if (input.media) {
        await supabase.from('blog_media').delete().eq('blog_post_id', id);

        if (input.media.length > 0) {
            const media = input.media.map((m, index) => ({
                blog_post_id: id,
                url: m.url,
                alt_text: m.alt_text || null,
                type: m.type || 'image',
                is_featured: m.is_featured ?? (index === 0),
                caption: m.caption || null,
                sort_order: index,
            }));

            const { error } = await supabase.from('blog_media').insert(media);
            if (error) {
                console.error('Error inserting blog media:', error);
                throw error;
            }
        }
    }

    // Fetch and return updated post
    const { data, error } = await supabase
        .from('blog_posts')
        .select('*')
        .eq('id', id)
        .single();

    if (error) throw error;
    return data as BlogPostRow;
}

/**
 * Delete a blog post (cascades to translations and media)
 */
export async function deleteBlogPost(id: string): Promise<void> {
    const supabase = getAdminClient();

    const { error } = await supabase
        .from('blog_posts')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting blog post:', error);
        throw error;
    }
}

/**
 * Publish a blog post
 */
export async function publishBlogPost(id: string): Promise<BlogPostRow> {
    const supabase = getAdminClient();

    const { data, error } = await supabase
        .from('blog_posts')
        .update({
            status: 'published',
            published_at: new Date().toISOString(),
        })
        .eq('id', id)
        .select()
        .single();

    if (error) {
        console.error('Error publishing blog post:', error);
        throw error;
    }

    return data as BlogPostRow;
}

/**
 * Unpublish a blog post
 */
export async function unpublishBlogPost(id: string): Promise<BlogPostRow> {
    const supabase = getAdminClient();

    const { data, error } = await supabase
        .from('blog_posts')
        .update({
            status: 'draft',
        })
        .eq('id', id)
        .select()
        .single();

    if (error) {
        console.error('Error unpublishing blog post:', error);
        throw error;
    }

    return data as BlogPostRow;
}

/**
 * Get all blog posts (for admin list view)
 */
export async function getAllBlogPosts(locale: Locale = 'vi'): Promise<BlogPostRow[]> {
    const supabase = getAdminClient();

    const { data, error } = await supabase
        .from('blog_posts')
        .select(`
      *,
      blog_translations (
        title,
        slug,
        locale
      )
    `)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching all blog posts:', error);
        throw error;
    }

    return data as BlogPostRow[];
}
