/**
 * Admin Products API Functions
 * Server-side CRUD operations for products
 */

import { getAdminClient } from '../supabaseClient';
import type {
    Locale,
    CreateProductRequest,
    ProductRow,
    ProductTranslationRow,
    ProductMediaRow,
    ProductExternalLinkRow,
} from '../types';

/**
 * Create a new product with translations, media, and external links
 */
export async function createProduct(input: CreateProductRequest): Promise<ProductRow> {
    const supabase = getAdminClient();

    // 1. Create base product
    const { data: product, error: productError } = await supabase
        .from('products')
        .insert({
            category_id: input.category_id || null,
            sku: input.sku || null,
            is_featured: input.is_featured ?? false,
            is_active: input.is_active ?? true,
            is_new: input.is_new ?? false,
        })
        .select()
        .single();

    if (productError) {
        console.error('Error creating product:', productError);
        throw productError;
    }

    // 2. Create translations
    if (input.translations && input.translations.length > 0) {
        const translations = input.translations.map((t) => ({
            product_id: product.id,
            locale: t.locale,
            name: t.name,
            slug: t.slug || null, // Will be auto-generated by trigger if null
            short_description: t.short_description || null,
            description: t.description || null,
            ingredients: t.ingredients || null,
            how_to_use: t.how_to_use || null,
            price: t.price || null,
            compare_price: t.compare_price || null,
            currency: t.currency || 'VND',
            seo_title: t.seo_title || null,
            seo_description: t.seo_description || null,
            seo_keywords: t.seo_keywords || null,
            og_image_url: t.og_image_url || null,
        }));

        const { error: translationError } = await supabase
            .from('product_translations')
            .insert(translations);

        if (translationError) {
            // Rollback: delete product
            await supabase.from('products').delete().eq('id', product.id);
            console.error('Error creating product translations:', translationError);
            throw translationError;
        }
    }

    // 3. Create media
    if (input.media && input.media.length > 0) {
        const media = input.media.map((m, index) => ({
            product_id: product.id,
            url: m.url,
            alt_text: m.alt_text || null,
            type: m.type || 'image',
            is_primary: m.is_primary ?? (index === 0),
            sort_order: m.sort_order ?? index,
        }));

        const { error: mediaError } = await supabase
            .from('product_media')
            .insert(media);

        if (mediaError) {
            console.error('Error creating product media:', mediaError);
            throw mediaError;
        }
    }

    // 4. Create external links
    if (input.external_links && input.external_links.length > 0) {
        const links = input.external_links.map((l, index) => ({
            product_id: product.id,
            platform: l.platform,
            url: l.url,
            label: l.label || null,
            locale: l.locale || null,
            is_active: l.is_active ?? true,
            sort_order: index,
        }));

        const { error: linkError } = await supabase
            .from('product_external_links')
            .insert(links);

        if (linkError) {
            console.error('Error creating external links:', linkError);
            throw linkError;
        }
    }

    return product as ProductRow;
}

/**
 * Update an existing product
 */
export async function updateProduct(
    id: string,
    input: Partial<CreateProductRequest>
): Promise<ProductRow> {
    const supabase = getAdminClient();

    // 1. Update base product if needed
    const productUpdate: Record<string, unknown> = {};
    if (input.category_id !== undefined) productUpdate.category_id = input.category_id;
    if (input.sku !== undefined) productUpdate.sku = input.sku;
    if (input.is_featured !== undefined) productUpdate.is_featured = input.is_featured;
    if (input.is_active !== undefined) productUpdate.is_active = input.is_active;
    if (input.is_new !== undefined) productUpdate.is_new = input.is_new;

    if (Object.keys(productUpdate).length > 0) {
        const { error: productError } = await supabase
            .from('products')
            .update(productUpdate)
            .eq('id', id);

        if (productError) {
            console.error('Error updating product:', productError);
            throw productError;
        }
    }

    // 2. Update translations (upsert by locale)
    if (input.translations) {
        for (const t of input.translations) {
            const { error } = await supabase
                .from('product_translations')
                .upsert({
                    product_id: id,
                    locale: t.locale,
                    name: t.name,
                    slug: t.slug,
                    short_description: t.short_description,
                    description: t.description,
                    ingredients: t.ingredients,
                    how_to_use: t.how_to_use,
                    price: t.price,
                    compare_price: t.compare_price,
                    currency: t.currency,
                    seo_title: t.seo_title,
                    seo_description: t.seo_description,
                    seo_keywords: t.seo_keywords,
                    og_image_url: t.og_image_url,
                }, { onConflict: 'product_id,locale' });

            if (error) {
                console.error('Error updating product translation:', error);
                throw error;
            }
        }
    }

    // 3. Replace media if provided
    if (input.media) {
        // Delete existing media
        await supabase.from('product_media').delete().eq('product_id', id);

        // Insert new media
        if (input.media.length > 0) {
            const media = input.media.map((m, index) => ({
                product_id: id,
                url: m.url,
                alt_text: m.alt_text || null,
                type: m.type || 'image',
                is_primary: m.is_primary ?? (index === 0),
                sort_order: m.sort_order ?? index,
            }));

            const { error } = await supabase.from('product_media').insert(media);
            if (error) {
                console.error('Error inserting product media:', error);
                throw error;
            }
        }
    }

    // 4. Replace external links if provided
    if (input.external_links) {
        await supabase.from('product_external_links').delete().eq('product_id', id);

        if (input.external_links.length > 0) {
            const links = input.external_links.map((l, index) => ({
                product_id: id,
                platform: l.platform,
                url: l.url,
                label: l.label || null,
                locale: l.locale || null,
                is_active: l.is_active ?? true,
                sort_order: index,
            }));

            const { error } = await supabase.from('product_external_links').insert(links);
            if (error) {
                console.error('Error inserting external links:', error);
                throw error;
            }
        }
    }

    // Fetch and return updated product
    const { data, error } = await supabase
        .from('products')
        .select('*')
        .eq('id', id)
        .single();

    if (error) throw error;
    return data as ProductRow;
}

/**
 * Delete a product (cascades to translations, media, links)
 */
export async function deleteProduct(id: string): Promise<void> {
    const supabase = getAdminClient();

    const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting product:', error);
        throw error;
    }
}

/**
 * Get all products (for admin list view)
 */
export async function getAllProducts(locale: Locale = 'vi'): Promise<ProductRow[]> {
    const supabase = getAdminClient();

    const { data, error } = await supabase
        .from('products')
        .select(`
      *,
      product_translations (
        name,
        slug,
        locale
      )
    `)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching all products:', error);
        throw error;
    }

    return data as ProductRow[];
}
